name: Deploy to EC2 Airflow

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dags/,plugins/,requirements.txt,docker-compose.yaml"
        target: "/home/ec2-user/airflow"
        strip_components: 0

    - name: Execute commands on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Check if configuration files were updated
          RESTART_NEEDED=false
          if [ -f ~/airflow/requirements.txt.original ] && ! cmp -s ~/airflow/requirements.txt ~/airflow/requirements.txt.original; then
            RESTART_NEEDED=true
          fi
          if [ -f ~/airflow/docker-compose.yaml.original ] && ! cmp -s ~/airflow/docker-compose.yaml ~/airflow/docker-compose.yaml.original; then
            RESTART_NEEDED=true
          fi
          
          # Save current versions as original
          cp ~/airflow/requirements.txt ~/airflow/requirements.txt.original
          cp ~/airflow/docker-compose.yaml ~/airflow/docker-compose.yaml.original
          
          # Restart Airflow if needed
          if [ "$RESTART_NEEDED" = true ]; then
            sudo systemctl restart airflow
          fi
          
          echo "Deployment completed successfully"