name: Deploy to EC2 Airflow

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Network Diagnostics
      run: |
        echo "GitHub Actions Runner IP: $(curl -s https://api.ipify.org)"
        
        # Verbose network test
        ssh -vvv \
          -o StrictHostKeyChecking=no \
          -i ~/.ssh/id_rsa \
          ec2-user@52.205.187.101 \
          'df -h && free -h && uptime'

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: 52.205.187.101
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dags/,plugins/,requirements.txt,docker-compose.yaml"
        target: "/home/ec2-user/airflow"
        strip_components: 0
        timeout: 15m
        command_timeout: 15m

    - name: Restart Airflow on EC2
      run: |
        # Prepare SSH key
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    
        # Verbose SSH command with extended timeout
        ssh -vvv \
          -o StrictHostKeyChecking=no \
          -o ServerAliveInterval=60 \
          -o ServerAliveCountMax=10 \
          -i ~/.ssh/id_rsa \
          ec2-user@${{ secrets.EC2_HOST }} \
          '
          set -x
          cd ~/airflow
          
          # Check if configuration files were updated
          RESTART_NEEDED=false
          if [ -f requirements.txt.original ] && ! cmp -s requirements.txt requirements.txt.original; then
            RESTART_NEEDED=true
          fi
          if [ -f docker-compose.yaml.original ] && ! cmp -s docker-compose.yaml docker-compose.yaml.original; then
            RESTART_NEEDED=true
          fi
          
          # Save current versions as original
          cp requirements.txt requirements.txt.original
          cp docker-compose.yaml docker-compose.yaml.original
          
          # Restart Airflow if needed
          if [ "$RESTART_NEEDED" = true ]; then
            echo "Restarting Airflow services..."
            docker compose pull
            docker compose down
            docker compose up -d
          else
            echo "No configuration changes detected. Skipping restart."
          fi
          
          echo "Deployment completed successfully"
          '